[package]
name = "louis_dor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "0.2"
rand = "0.7"
rustc-serialize = "0.3.24"
ed25519-dalek = "1.0.0-pre.3"